name: Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

      - name: Build CLI binary
        run: ./bin/task build

      - name: Upload CLI binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloudstart
          path: .bin/cloudstart

  tag-and-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download CLI binary artifact
        uses: actions/download-artifact@v4
        with:
          name: cloudstart
          path: .bin/

      - name: Move binary to root for release
        run: mv .bin/cloudstart ./cloudstart

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main
          tag_prefix: v

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: "Cloudstart CLI ${{ steps.tag_version.outputs.new_tag }}"
          body: "Automated release for ${{ steps.tag_version.outputs.new_tag }}"
          files: ./cloudstart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 